// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2MHmx4Q2_bjFmRIgRIKzdq6vOKR1MJ2g',
    appId: '1:416404078273:web:eccafa44a7900353591e40',
    messagingSenderId: '416404078273',
    projectId: 'task-manager-7cd3d',
    authDomain: 'task-manager-7cd3d.firebaseapp.com',
    storageBucket: 'task-manager-7cd3d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZCd9ybhqBtLXTLB3t0LwTwSj552ZUAMo',
    appId: '1:416404078273:android:e99b22f0f62fcf8a591e40',
    messagingSenderId: '416404078273',
    projectId: 'task-manager-7cd3d',
    storageBucket: 'task-manager-7cd3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqgUK4PCrVS6GjPpyQX16kle9dch71OCE',
    appId: '1:416404078273:ios:53873a58609ec8a6591e40',
    messagingSenderId: '416404078273',
    projectId: 'task-manager-7cd3d',
    storageBucket: 'task-manager-7cd3d.firebasestorage.app',
    iosBundleId: 'com.example.testingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqgUK4PCrVS6GjPpyQX16kle9dch71OCE',
    appId: '1:416404078273:ios:53873a58609ec8a6591e40',
    messagingSenderId: '416404078273',
    projectId: 'task-manager-7cd3d',
    storageBucket: 'task-manager-7cd3d.firebasestorage.app',
    iosBundleId: 'com.example.testingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2MHmx4Q2_bjFmRIgRIKzdq6vOKR1MJ2g',
    appId: '1:416404078273:web:322f30bd2d56bce1591e40',
    messagingSenderId: '416404078273',
    projectId: 'task-manager-7cd3d',
    authDomain: 'task-manager-7cd3d.firebaseapp.com',
    storageBucket: 'task-manager-7cd3d.firebasestorage.app',
  );
}
